config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("portfolio.users.urls", namespace="users")),
    path("map/", include("portfolio.map.urls", namespace="map")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

portfolio/map/urls.py
from django.urls import path

from portfolio.map.views import map_view

app_name = "map"
urlpatterns = [
    path("", view=map_view, name="map"),
]

portfolio/users/urls.py
from django.urls import path

from portfolio.users.views import user_detail_view, user_redirect_view, user_update_view

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

portfolio/map/models.py
# from django.contrib.gis.db import models

# from portfolio.users.models import User


# class UserLocation(models.Model):
#     user = models.ForeignKey(User, on_delete=models.CASCADE)
#     location = models.PointField()

portfolio/projects/models.py
from django.conf import settings
from django.db import models
from django.utils.translation import gettext_lazy as _


class Project(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="user_projects",
        related_query_name="user_project",
        on_delete=models.CASCADE,
    )
    title = models.CharField(_("Title"), max_length=255)
    description = models.TextField(_("Description"))
    image = models.ImageField(
        _("Image"), upload_to="project_images", null=True, blank=True
    )
    link = models.URLField(_("Link"), max_length=200, null=True, blank=True)

    def __str__(self):
        return self.title

portfolio/users/models.py
from django.contrib.auth.models import AbstractUser
from django.contrib.gis.db import models
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

# from PIL import Image


class User(AbstractUser):
    """
    Default custom user model for portfolio.
    If adding fields that need to be filled at user signup,
    check forms.SignupForm and forms.SocialSignupForms accordingly.
    """

    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore
    name = CharField(_("Name of User"), blank=True, max_length=255)
    home_address = models.CharField(_("Home Address"), blank=True, max_length=255)
    phone_number = models.CharField(_("Phone Number"), blank=True, max_length=20)
    location = models.PointField(_("Location"), blank=True, null=True)
    profile_picture = models.ImageField(
        _("Profile Picture"),
        upload_to="profile_pics/",
        blank=True,
        null=True,
        default="default.jpg",
    )
    bio = models.TextField(_("About Me"), blank=True, max_length=1000)
    profession = models.CharField(_("Profession"), blank=True, max_length=40)
    projects = models.ManyToManyField(
        "projects.Project", blank=True, related_name="projects"
    )

    def save(self, *args, **kwargs):
        """
        This function resizes a profile picture before saving it.
        """
        """Override the save method to resize the profile picture before saving it"""
        super().save(*args, **kwargs)

        # if self.profile_picture:
        #     img = Image.open(self.profile_picture.path)

        #     if img.height > 300 or img.width > 300:
        #         output_size = (300, 300)
        #         img.thumbnail(output_size)
        #         img.save(self.profile_picture.path)

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})


class UserProject(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    project = models.ForeignKey("projects.Project", on_delete=models.CASCADE)
    date_joined = models.DateField(auto_now_add=True)

    class Meta:
        unique_together = ("user", "project")

portfolio/projects/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from .models import Project


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = [
            "title",
            "description",
            "image",
            "link",
        ]
        widgets = {
            "title": forms.TextInput(
                attrs={"class": "form-control", "placeholder": _("Title")}
            ),
            "description": forms.Textarea(
                attrs={
                    "class": "form-control",
                    "placeholder": _("Description"),
                    "rows": 3,
                }
            ),
            "link": forms.URLInput(
                attrs={"class": "form-control", "placeholder": _("Link")}
            ),
            "image": forms.FileInput(attrs={"class": "form-control-file"}),
        }

portfolio/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.forms.models import inlineformset_factory
from django.utils.translation import gettext_lazy as _

from portfolio.projects.forms import ProjectForm
from portfolio.projects.models import Project

User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """


ProjectFormSet = inlineformset_factory(
    User,
    Project,
    form=ProjectForm,
    fields=["title", "description", "image", "link"],
    extra=1,
    can_delete=True,
)

portfolio/map/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import TemplateView

from portfolio.users.models import User


class MapView(LoginRequiredMixin, TemplateView):
    template_name = "map/map.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_locations = User.objects.all()
        user_data = []
        if user_locations:
            for user_location in user_locations:
                # create a Point object from the PostGIS geometry
                point = user_location.location
                lat = point.y
                lng = point.x
                user_data.append(
                    {
                        "name": user_location.username,
                        "lat": lat,
                        "lng": lng,
                        "url": reverse("users:detail", args=[user_location.pk]),
                        "profile_picture": user_location.profile_picture.url
                        if user_location.profile_picture
                        else "",
                        "profession": user_location.profession
                        if user_location.profession
                        else "",
                        "bio": user_location.bio if user_location.bio else "",
                    }
                )
        context["user_data"] = user_data
        return context


map_view = MapView.as_view()

portfolio/users/views.py
import time

from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.gis.geos import Point
from django.contrib.messages.views import SuccessMessageMixin
from django.forms import inlineformset_factory
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView
from geopy.exc import GeocoderTimedOut

from portfolio.projects.models import Project

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"
    context_object_name = "user"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.object
        projects = Project.objects.filter(user=user)
        context["projects"] = projects
        return context


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    fields = [
        "name",
        "home_address",
        "phone_number",
        "profession",
        "profile_picture",
        "bio",
    ]
    success_message = _("Information successfully updated")

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        if self.request.POST:
            data["project_formset"] = ProjectFormSet(
                self.request.POST, self.request.FILES, instance=self.object
            )
        else:
            data["project_formset"] = ProjectFormSet(instance=self.object)
        return data

    def form_valid(self, form):
        project_formset = ProjectFormSet(
            self.request.POST, self.request.FILES, instance=self.get_object()
        )
        if project_formset.is_valid():
            project_formset.save()

        # Set the location field based on the home address field
        address = form.cleaned_data.get("home_address")
        if address:
            # Use a geocoding service to get the latitude and longitude of the address
            # and create a Point object with the coordinates
            # For example, using geopy:
            from geopy.geocoders import Nominatim

            geolocator = Nominatim(user_agent="portfolio")
            location = None
            retries = 3
            backoff = 1
            while retries > 0:
                try:
                    location = geolocator.geocode(address, timeout=10)
                    break
                except (GeocoderTimedOut, ConnectionError):
                    retries -= 1
                    if retries == 0:
                        # If all retries fail, raise an exception
                        raise
                    time.sleep(backoff)
                    backoff *= 2
            if location:
                point = Point(location.longitude, location.latitude)
                form.instance.location = point

        return super().form_valid(form)

    def get_success_url(self):
        assert (
            self.request.user.is_authenticated
        )  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self, queryset=None):
        queryset = queryset or self.get_queryset()
        return queryset.get(pk=self.request.user.pk)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()


ProjectFormSet = inlineformset_factory(
    User, Project, fields=("title", "description", "image", "link"), extra=1
)  # type: ignore

portfolio/templates/base.html
{% load leaflet_tags %}
{% load static i18n %}<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE }}">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}portfolio{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Behold My Awesome Project!">
    <meta name="author" content="Daniel Selenge Kamanda">

    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">

    {% block css %}
    <!-- Latest compiled and minified Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.3/css/bootstrap.min.css" integrity="sha512-GQGU0fMMi238uA+a/bdWJfpUGKUkBdgfFdgBm72SUQ6BeyWjoY/ton0tEjH+OSH9iP4Dfh+7HM0I9f5eR0L/4w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!-- Your stuff: Third-party CSS libraries go here -->

    <!-- Leaflet CSS -->
    <link rel="stylesheet" href="{% static 'leaflet/leaflet.css' %}" integrity="">

    <!-- This file stores project-specific CSS -->
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    {% endblock %}
    <!-- Le javascript
    ================================================== -->
    {# Placed at the top of the document so pages load faster with defer #}
    {% block javascript %}
      <!-- Bootstrap JS -->
      <script defer src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.3/js/bootstrap.min.js" integrity="sha512-OvBgP9A2JBgiRad/mM36mkzXSXaJE9BEIENnVEmeZdITvwT09xnxLtT4twkCa8m/loMbPHsvPl0T8lRGVBwjlQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
      <!-- Your stuff: Third-party javascript libraries go here -->

      <!-- Leaflet JS -->
      <script src="{% static 'leaflet/leaflet.js' %}" integrity=""></script>

      <!-- place project specific Javascript in this file -->
      <script defer src="{% static 'js/project.js' %}"></script>

    {% endblock javascript %}

  </head>

  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">Portfolio</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ms-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home' %}">Home <span class="visually-hidden">(current)</span></a>
            </li>
            {% if request.user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% translate "My Profile" %}</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  {% translate "Account" %}
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <li><a class="dropdown-item" href="{% url 'account_email' %}">{% translate "Change Email" %}</a></li>
                  <li><a class="dropdown-item" href="{% url 'users:update' %}">{% translate "Edit Profile" %}</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="{% url 'account_logout' %}">{% translate "Sign Out" %}</a></li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'map:map' %}">Map</a>
              </li>
            {% else %}
              {% if ACCOUNT_ALLOW_REGISTRATION %}
                <li class="nav-item">
                  <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% translate "Sign Up" %}</a>
                </li>
              {% endif %}
              <li class="nav-item">
                <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% translate "Sign In" %}</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>

    <div class="">

      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-dismissible {% if message.tags %}alert-{{ message.tags }}{% endif %}">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        {% endfor %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->

    <footer class="text-center footer">
      {% block footer %}
      {% endblock %}

      <div class="text-center text-black copyright py-4">
        <div class="container">
          <small>Copyright ©&nbsp;Portfolio 2023</small>
        </div>
      </div>
		</footer>

    {% block modal %}{% endblock modal %}

    {% block inline_javascript %}
    {% comment %}
    Script tags with only code, no src (defer by default). To run
    with a "defer" so that you run inline code:
    <script>
      window.addEventListener('DOMContentLoaded', () => {/* Run whatever you want */});
    </script>
    {% endcomment %}
    {% endblock inline_javascript %}

    {% block scripts %}{% endblock %}
  </body>
</html>